name: test

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # 롤백(git reset)을 위해 이전 이력까지 가져옵니다.
	
      - name: Run
        id: deploy_step # 롤백 판단을 위해 ID를 꼭 붙여야 합니다.
        run: |
          
          echo "내 서버에서 앱을 실행합니다."
          # 실패 시 에러를 뱉도록 설정 (npm run start:dev가 실패하면 롤백으로 넘어감)
          npm run start:dev

      - name: Save Success State
        if: success()
        run: |
          
          pm2 save
          echo "배포 성공!"

      - name: Automatic Rollback
        if: failure() && steps.deploy_step.outcome == 'failure'
        run: |
          echo "⚠️ 배포 실패 감지! 롤백을 시작합니다."

          # 코드를 이전 커밋으로 되돌림
          # git reset --hard HEAD@{1}
          
          # 이전 코드로 다시 빌드
          
          npm run start:dev
          
          echo "🚨 이전 성공 버전으로 자동 복구되었습니다. 코드를 확인하세요!"
