name: test

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check Current Directory
        run: pwd

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: install and build
        run: |
          echo "내 서버에서 빌드를 시작합니다."
          npm install
          npm run build  # run을 붙여야 실행됩니다.

      - name: Run
        working-directory: /Users/keh/Desktop/appl/api-template-nest
        id: deploy_step
        run: |
          echo "내 서버에서 앱을 실행합니다."
          npm run start:dev
         
      - name: Save Success State
        if: success()
        run: |
          pm2 save
          echo "배포 성공!"

      - name: Automatic Rollback
        if: failure() && steps.deploy_step.outcome == 'failure'
        # 롤백 시에도 해당 디렉토리로 이동해야 합니다.
        working-directory: /Users/keh/Desktop/appl/api-template-nest
        run: |
          echo "⚠️ 배포 실패 감지! 롤백을 시작합니다."
          # git reset --hard HEAD@{1}
          npm run start:dev
          echo "🚨 이전 성공 버전으로 자동 복구되었습니다."
